version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FRANKENPHP_CONFIG: worker ./public/index.php 1
      MAX_REQUESTS: 100
    volumes:
      - .:/app
    ports:
      - 80:80
      - 443:443

